//import Main from "./01.Hello World/01"
//import Main from "./02.Introducing JSX/01"
//import Main from "./03.Rendering Elements/02"
//import Main from "./04.Components and Props/01"
//import Main from "./04.Components and Props/02. Composing Components"
//import Main from "./05.State and Lifecycle/01"
//import Main from "./05.State and Lifecycle/02"
//import Main from "./05.State and Lifecycle/04.Adding Lifecycle Methods to a Class"
//import Main from "./06.Handling Events/01"
//import Main from "./06.Handling Events/02"
//import Main from "./07.Conditional Rendering/02"
//import Main from "./07.Conditional Rendering/04.Inline If-Else with Conditional Operator"
//import Main from "./07.Conditional Rendering/05.Preventing Component from Rendering"
//import Main from "./08.Lists and Keys/01"
//import Main from "./08.Lists and Keys/02.Basic List Component"
//import Main from "./08.Lists and Keys/03.Keys"
//import Main from "./08.Lists and Keys/04.Embedding map() in JSX"
//import Main from "./09.Forms/01.Controlled Components"
//import Main from "./09.Forms/02.The select Tag"
//import Main from "./09.Forms/03.Handling Multiple Inputs"
import Main from "./09.Forms/04.TestForm"
//import Main from "./10.Lifting State Up/01"
//import Main from "./11.Composition vs Inheritance/01"


new Main();